require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/players', type: :request do
  describe 'GET /index' do
    let(:valid_attributes) do
      { name: 'Name', team: 'Team', position: 'Position', attempts_per_game: 2.5, total_attempts: 3, total_yards: 4,
        average_yards_per_attempt: 5.5, yards_per_game: 6.5, rushing_touchdowns: 7, longest_rush: 8,
        longest_rush_is_touchdown: false, first_downs: 9, first_downs_percent: 10.5, twenty_plus: 11,
        forty_plus: 12, fumbles: 13 }
    end
    it 'renders a successful response' do
      Player.create! valid_attributes
      get players_url
      expect(response).to be_successful
    end
  end
end
